Add alert CDIMultipleDefaultVirtStorageClasses
kubevirt/monitoring pull request #201
Opened 2023-10-10 15:05 UTC by akalenyu

Related to https://github.com/kubevirt/containerized-data-importer/pull/2913 efforts

2023-10-19 18:35 UTC, akalenyu commented
/cc @sradco

2023-10-22 11:06 UTC, apinnick requested changes

2023-10-22 11:06 UTC, apinnick commented on docs/runbooks/CDIMultipleDefaultVirtStorageClasses.md
> +Observe multiple storage classes are marked as default for virtualization purposes:
Suggestion:

Obtain a list of default virtualization storage classes by running the following command:

2023-10-22 11:06 UTC, apinnick commented on docs/runbooks/CDIMultipleDefaultVirtStorageClasses.md
> +Ensure the default virtualization storage class annotation is only present on a single storage class of your choice.
Suggestion: 

Ensure that only one storage class has the default virtualization storage class annotation.

2023-10-22 11:08 UTC, apinnick commented
@akalenyu Is this alert for 4.14?

2023-10-22 11:08 UTC, akalenyu commented
> @akalenyu Is this alert for 4.14?

4.15

2023-10-24 11:51 UTC, akalenyu commented
@sradco @apinnick addressed comments

2023-10-30 13:48 UTC, sradco commented
/lgtm

@apinnick Can I merge ?

2023-10-30 13:50 UTC, apinnick commented
/lgtm

2023-11-16 10:04 UTC, sradco approved these changes

2023-11-16 10:05 UTC, merged

2023-11-16 11:19 UTC, apinnick commented
D/S runbook task for 4.15 - CNV-35292