runbooks, Add info about KubeMacPoolDuplicateMacsFound runbook
kubevirt/monitoring pull request #23
Opened 2021-08-08 11:23 UTC by oshoval

Signed-off-by: Or Shoval <oshoval@redhat.com>

2021-08-08 11:24 UTC, oshoval commented
/cc @RamLavi 

I will add the prints of vm / interface, mac that are mentioned, on the kubemacpool PR

2021-08-08 11:28 UTC, oshoval commented
trying to generate the list

```
monitoring (dup) $ python automation/generate_pages_index.py
  File "automation/generate_pages_index.py", line 20
    lines = list(map(lambda f: f"* [{f[:-3]}]({f})\n", files))
                                                    ^
SyntaxError: invalid syntax
```

2021-08-08 13:44 UTC, RamLavi requested changes

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Upon starting KubeMacPool, it scan the current VM instances and updates it's database.
```suggestion
Upon starting KubeMacPool, it scans the cluster for MAC Addresses in VMs set on the managed namespaces.
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +In case it find duplicates it increase a counter of mac duplicate, which results in this alert.
```suggestion
In case it finds duplicates it will raise this alert.
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +KubeMacPool is responsible to allocate mac addresses and avoid mac address conflicts.
```suggestion
KubeMacPool is responsible to allocate MAC Addresses and prevent MAC Address conflicts.
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Duplicates will not be updated in the database but do exists until solved.
This is not accurate, I would vote to remove this line.. we should keep the explanation generic and simple
```suggestion
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Having a duplicate mac address can break the requirement that each interface on the same LAN,
```suggestion
Having a duplicate MAC Addresses can break the requirement that each interface on the same LAN,
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +should have a unique mac address.
```suggestion
should have a unique MAC Address.
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +- Check the logs of kubemacpool-mac-controller, find the lines that say
I would be more specific.. don't expect the sys-admin to know what's KMP's namespace
```
- Get kubemacpool-mac-controller pod namespace + command example
- Extract the conflicting VMs from kubemacpool pod logs, from which you will have 1, 2 and 3: + command example
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Remove or update mac addresses that were assigned manually or before kubemacpool was deployed or opted in.
```suggestion
Update the VMs to remove the duplicate MAC Addresses.
```

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Once all the conflicts are resolved, restart the `kubemacpool-mac-controller` pod,
please add command example

2021-08-08 13:44 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +in order to rescan and rebuild the database.
I would remove this line, no further details needed imo.

2021-08-09 07:06 UTC, oshoval commented
Addressed comments, thanks

2021-08-09 07:12 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +Having a duplicate MAC Addresses can break the requirement that each interface on the same LAN,
can we rephrase this? something like 
```suggestion
Duplicate MAC Addresses on the same LAN may cause unexpected and various connectability issues in the network.
```

2021-08-09 07:14 UTC, RamLavi commented on docs/runbooks/KubeMacPoolDuplicateMacsFound.md
> +  `kubectl get pod -A -l control-plane=mac-controller-manager --no-headers -o custom-columns=":metadata.namespace,:metadata.name"`
This line appears in the same line when looking in the `Display rich format` option, I think you need to add a new line. also in the rest

2021-08-09 07:36 UTC, oshoval commented
Addressed comments

2021-08-16 13:24 UTC, RamLavi approved these changes
/lgtm

/hold
until we merge this alert on CNAO

2021-08-17 07:24 UTC, oshoval commented
Thanks
@sradco can you take a look please?

2021-08-17 07:42 UTC, sradco commented
/lgtm

2021-08-29 06:23 UTC, oshoval commented
> @oshoval can we wait until the actual alert is added on [kubevirt/cluster-network-addons-operator#952](https://github.com/kubevirt/cluster-network-addons-operator/pull/952)?

shouldn't it be the opposite ?
but anyway we can merge that one already i think ?

2021-08-30 07:17 UTC, RamLavi commented
/hold cancel
@sradco I'm good when you are ready to merge this PR

2021-08-30 08:03 UTC, merged